### ISSUE TITLE
StockOptions Order requires "ToOpenClose" 

### ISSUE THREAD

**Issue by vinutshetty** [hootnot/saxo_openapi#10]
StockOptions Order requires "ToOpenClose" attribute which is not part of the current 
_[saxo_openapi/saxo_openapi/contrib/orders/limitorder.py](url)_ 

OpenAPIError: HTTP error: 400, reason: Bad Request, errorcontent: {"Message":"One or more properties of the request are invalid!","ModelState":{"ToOpenClose":["ToOpenClose must be set to either ToClose or ToOpen when AssetType=FuturesOption,StockIndexOption,StockOption,CfdIndexOption"]},"ErrorCode":"InvalidModelState"}

**Comment by vinutshetty** [comment]
this also applies for OnFill TakeProfit

**Comment by hootnot** [comment]
Hi,

*contrib* module contains code to make it a easier to construct orders.

It contains a base class *LimitOrder* and 2 classes derived from that
class:

  - LimitOrderFxSpot
  - LimitOrderStock

At SAXO you can trade a lot of instruments and the *contrib* module
covers **FX** and **Stock** related instrument types.

Feel free to create a *LimitOrderOption* yourself to handle **Options**.

Constructing the orderbody as you need it and pass it to
*tr.orders.Order(...)* as in
https://saxo-openapi.readthedocs.io/en/latest/endpoints/trading/orders/Order.html
should work fine.
