### ISSUE TITLE
Fetching data via the websocket

### ISSUE THREAD

**Issue by sword134** [hootnot/saxo_openapi#13]
Hello,
I am loving this repo but have so far been using `chart.charts.GetChartData(params=params)` to get my data. To no ones surprise, this got the token unauthorized in the end. I am now looking into streaming the price data that I need to make the calculations before sending an order to Saxo. I am just not quite sure on how to do it, on developer.saxo I have setup a stream that streams the 5 min data of EUR/USD and it works in the developer.saxo WebSocket terminal. However, how do I actually access this data via python? I have no experience what so ever with WebSockets so connecting to one and fetching its data is something completely new to me.

**Comment by hootnot** [comment]
There is an example regarding streaming prices: https://saxo-openapi.readthedocs.io/en/latest/examples/stream_proc.html

Every message you receive can be dispatched for processing the way you want. That might be processing by some piece of code in the program that does the streaming, but you can also opt for some messaging concept that allows you to process those price records in multiple ways by having applications subscribing for messages.

Hope that helps a bit.

**Comment by sword134** [comment]
@hootnot When I create a data subscription to EURUSD it successfully adds it, however the code specified here regarding the streaming of the data, does not print anything to the terminal:

```
import asyncio
import websockets
from saxo_openapi.contrib.ws import stream


async def echo(ContextId, token):
    hdrs = {
        "Authorization": "Bearer {}".format(token),
    }
    URL = "wss://streaming.saxotrader.com/sim/openapi/streamingws/connect?" + \
          "contextId={ContextId}".format(ContextId=ContextId)
    async with websockets.connect(URL, extra_headers=hdrs) as websocket:
        async for message in websocket:
            print(stream.decode_ws_msg(message))

if __name__ == "__main__":
    import sys

    with open("token.txt") as I:
        token = I.read().strip()

    asyncio.get_event_loop().run_until_complete(Echo(ContextId=sys.argv[1],
                                                     token=token))
```

**Comment by sword134** [comment]
And yes I am inputting the token and correct contextid. Also, note that the function name echo needs to be changed to Echo or it throws a syntax error.

**Comment by sword134** [comment]
Ok I actually found the solution. For future users note the following:

DO NOT use the contextId that is generated via saxo.developer under their datastream, simply just make your own!

**Comment by hootnot** [comment]
Check https://saxo-openapi.readthedocs.io/en/latest/examples/stream_proc.html

You need both programs. The first one reads the stream. When you start it you will get no output since there are no subscriptions yet. (there is a typo in the program: rename *async def echo* to **async def Echo**

The other program allows you to subscribe for data, when you've done  that the data will appear on your screen.

So you do:

```
$ python python stream_example.py ctxt_20210219
```

and from another shell: 

```
$ python price_subscr.py ctxt_20210219 EURJPY EURGBP
Subscription for instrument: EURJPY succesful
Subscription for instrument: EURGBP succesful
check the stream for data ...
```

and you get:

```
{'refid': b'EURJPY', 'msgId': 1, 'msg': {'LastUpdated': '2021-02-19T09:32:15.167000Z', 'Quote': {'Ask': 127.902, 'Bid': 127.867, 'Mid': 127.8845}}}
{'refid': b'EURGBP', 'msgId': 2, 'msg': {'LastUpdated': '2021-02-19T09:32:15.991000Z'}}
{'refid': b'EURJPY', 'msgId': 3, 'msg': {'LastUpdated': '2021-02-19T09:32:16.311000Z', 'Quote': {'Ask': 127.9, 'Bid': 127.865, 'Mid': 127.8825}}}
{'refid': b'EURGBP', 'msgId': 4, 'msg': {'LastUpdated': '2021-02-19T09:32:19.305000Z', 'Quote': {'Ask': 0.86722, 'Bid': 0.86692, 'Mid': 0.86707}}}
{'refid': b'EURJPY', 'msgId': 5, 'msg': {'LastUpdated': '2021-02-19T09:32:19.950000Z', 'Quote': {'Ask': 127.904, 'Bid': 127.869, 'Mid': 127.8865}}}
{'refid': b'EURGBP', 'msgId': 6, 'msg': {'LastUpdated': '2021-02-19T09:32:20.334000Z', 'Quote': {'Ask': 0.86723, 'Bid': 0.86693, 'Mid': 0.86708}}}
{'refid': b'EURJPY', 'msgId': 7, 'msg': {'LastUpdated': '2021-02-19T09:32:20.826000Z', 'Quote': {'Ask': 127.903, 'Bid': 127.868, 'Mid': 127.8855}}}
{'refid': b'EURGBP', 'msgId': 8, 'msg': {'LastUpdated': '2021-02-19T09:32:21.164000Z', 'Quote': {'Ask': 0.86725, 'Bid': 0.86695, 'Mid': 0.8671}}}
{'refid': b'EURGBP', 'msgId': 9, 'msg': {'LastUpdated': '2021-02-19T09:32:22.351000Z', 'Quote': {'Ask': 0.86727, 'Bid': 0.86697, 'Mid': 0.86712}}}
{'refid': b'EURGBP', 'msgId': 10, 'msg': {'LastUpdated': '2021-02-19T09:32:23.342000Z', 'Quote': {'Ask': 0.86729, 'Bid': 0.86699, 'Mid': 0.86714}}}
{'refid': b'EURJPY', 'msgId': 11, 'msg': {'LastUpdated': '2021-02-19T09:32:23.820000Z', 'Quote': {'Ask': 127.907, 'Bid': 127.872, 'Mid': 127.8895}}}
{'refid': b'EURJPY', 'msgId': 12, 'msg': {'LastUpdated': '2021-02-19T09:32:25.156000Z', 'Quote': {'Ask': 127.908, 'Bid': 127.873, 'Mid': 127.8905}}}
{'refid': b'EURGBP', 'msgId': 13, 'msg': {'LastUpdated': '2021-02-19T09:32:25.172000Z', 'Quote': {'Ask': 0.86731, 'Bid': 0.86701, 'Mid': 0.86716}}}
{'refid': b'EURGBP', 'msgId': 14, 'msg': {'LastUpdated': '2021-02-19T09:32:26.315000Z', 'Quote': {'Ask': 0.8673, 'Bid': 0.867, 'Mid': 0.86715}}}
{'refid': b'EURJPY', 'msgId': 15, 'msg': {'LastUpdated': '2021-02-19T09:32:27.111000Z', 'Quote': {'Ask': 127.907, 'Bid': 127.872, 'Mid': 127.8895}}}
{'refid': b'EURGBP', 'msgId': 16, 'msg': {'LastUpdated': '2021-02-19T09:32:27.351000Z', 'Quote': {'Ask': 0.86723, 'Bid': 0.86693, 'Mid': 0.86708}}}
{'refid': b'EURJPY', 'msgId': 17, 'msg': {'LastUpdated': '2021-02-19T09:32:28.121000Z', 'Quote': {'Ask': 127.909, 'Bid': 127.874, 'Mid': 127.8915}}}
{'refid': b'EURGBP', 'msgId': 18, 'msg': {'LastUpdated': '2021-02-19T09:32:29.251000Z', 'Quote': {'Ask': 0.86721, 'Bid': 0.86691, 'Mid': 0.86706}}}

```
