### ISSUE TITLE
Use App instead of 24h token

### ISSUE THREAD

**Issue by HumbleKazoku** [hootnot/saxo_openapi#18]
Been using this great library for a while with the 24h token. Is there a way to authorize and use Saxo Apps.  I have the following but can't figure out where to use them to get a client/API:
- App Key
- Grant Type
- Authorization Endpoint
- Token Endpoint
- Redirect URLs
- App Secrets
Is it possible to use this library with an 'app' instead of updating the token every 24h?

**Comment by hootnot** [comment]
yes, setting up the OAuth2 flow to refresh tokens that can be done. I have it running in a docker container

**Comment by HumbleKazoku** [comment]
Great. Is that refreshing the 24h code or using Saxo Apps and their App and Secret keys?

**Comment by HumbleKazoku** [comment]
OK good its an application. I have one ready with the live account as well. So when using this package where do you put the token, secret, endpoint urls etc.?

In the examples, one creates the API client with the 24h token.

**Comment by hootnot** [comment]
The OAuth2 flow is something apart from your application. It only maintains the token. So, once you've set up the OAuth flow you are able to refresh the token every 20 minutes. 
The application you have needs to refresh it's token by getting the latest valid one. If you have some command line application you simply read the latest token when running the application (assuming it is done within 20 minutes). If you have some application running 24/7 you need to code the refreshing by knowing  when the token you use becomes invalid and then refresh

**Comment by HumbleKazoku** [comment]
I see. So you're saying the OAuth2 can be a separate program that uses the Saxo Application App Key and Secrets etc. and this produces a token, which can then be used in the place of the 24h token?

Is it possible you have an example to help my understanding?

**Comment by hootnot** [comment]
What OS do you run?

**Comment by HumbleKazoku** [comment]
Ubuntu

**Comment by hootnot** [comment]
Ok, I'll come back to it and see if I can get it turn-key to you (not today, likely tomorrow)

**Comment by HumbleKazoku** [comment]
Would be awesome, thanks!

**Comment by HumbleKazoku** [comment]
Any update?

**Comment by hootnot** [comment]
I have this code in a private repo currently. I will verify it tomorrow and send you an invite to access that repo after I've verified things.

**Comment by HumbleKazoku** [comment]
Great, thanks!

**Comment by HumbleKazoku** [comment]
Thanks!
