### ISSUE TITLE
404 on ContractoptionSpaces

### ISSUE THREAD

**Issue by cottrell** [hootnot/saxo_openapi#5]
The following sort of works up to the point of pulling the options prices:

```
r = rd.instruments.Instruments(params = {'AccountKey': ai.AccountKey,
                                         'KeyWords': 'GBPUSD',
                                         'AssetTypes': ','.join([AT.FxSpot, AT.FxForwards, AT.FxVanillaOption])})
print(json.dumps(client.request(r), indent=2))

{
  "Data": [
    {
      "AssetType": "FxSpot",
      "CurrencyCode": "USD",
      "Description": "British Pound/US Dollar",
      "ExchangeId": "SBFX",
      "GroupId": 29721,
      "Identifier": 31,
      "IsKeywordMatch": true,
      "SummaryType": "Instrument",
      "Symbol": "GBPUSD",
      "TradableAs": [
        "FxSpot",
        "FxForwards",
        "FxVanillaOption",
        "FxKnockInOption",
        "FxKnockOutOption",
        "FxOneTouchOption",
        "FxNoTouchOption"
      ]
    },
    {
      "AssetType": "FxVanillaOption",
      "CurrencyCode": "USD",
      "Description": "British Pound/US Dollar",
      "ExchangeId": "SBFX",
      "GroupId": 29721,
      "Identifier": 31,
      "IsKeywordMatch": true,
      "SummaryType": "Instrument",
      "Symbol": "GBPUSD",
      "TradableAs": [
        "FxSpot",
        "FxForwards",
        "FxVanillaOption",
        "FxKnockInOption",
        "FxKnockOutOption",
        "FxOneTouchOption",
        "FxNoTouchOption"
      ]
    },
    {
      "AssetType": "FxForwards",
      "CurrencyCode": "USD",
      "Description": "British Pound/US Dollar",
      "ExchangeId": "SBFX",
      "GroupId": 29721,
      "Identifier": 31,
      "SummaryType": "Instrument",
      "Symbol": "GBPUSD",
      "TradableAs": [
        "FxSpot",
        "FxForwards",
        "FxVanillaOption",
        "FxKnockInOption",
        "FxKnockOutOption",
        "FxOneTouchOption",
        "FxNoTouchOption"
      ]
    }
  ]
}

r = rd.instruments.ContractoptionSpaces(29721)
client.request(r)

---------------------------------------------------------------------------
OpenAPIError                              Traceback (most recent call last)
<ipython-input-77-658528c00c6e> in <module>
      1 r = rd.instruments.ContractoptionSpaces(29721)
----> 2 client.request(r)

~/anaconda3/envs/gi/lib/python3.7/site-packages/saxo_openapi/saxo_openapi.py in request(self, endpoint)
    208                                       url,
    209                                       request_args,
--> 210                                       headers=headers)
    211             if (hasattr(endpoint, "RESPONSE_DATA") and
    212                     getattr(endpoint, "RESPONSE_DATA") is None):

~/anaconda3/envs/gi/lib/python3.7/site-packages/saxo_openapi/saxo_openapi.py in __request(self, method, url, request_args, headers, stream)
    143             raise OpenAPIError(response.status_code,
    144                                response.reason,
--> 145                                response.content.decode('utf-8'))
    146         return response
    147 

OpenAPIError: HTTP error: 404, reason: Not Found
```

**Comment by cottrell** [comment]
Also same thing on using 31. I've also tried the Shell example in the notebooks and it has same error.

**Comment by hootnot** [comment]
I hope you can imagine that I can't give support on this kind of questions. You really need to figure out things yourself.

If you run into a bug I will of course pay attention. You get a 404 which clearly is a response from SAXO. So, please check the parameters you pass etc. You can also try their online interface to the API: the explorer. If you have an error using `saxo_openapi` but you don' t have it using the explorer or `curl`, then I'll take a look.

Good luck!

**Comment by cottrell** [comment]
Yeah, possible but I would suggest some round trip tests because the examples involve taking ONE reponse to construct another request and then getting that response. If *that* doesn't work then it could be Saxo or something else. 

I'll drop to the REST api to debug and will try to PR anything useful I find.

**Comment by gidven** [comment]
404 not found is a Saxo response indicating that the instrument was.. not found. If I have to guess, this is because your sim account has not been configured for these products (do you find options in STGO?).

**Comment by cottrell** [comment]
@gidven Interesting. I did not see anywhere in the docs where view only was limited. I have options and most products avail in my regular accounts.

**Comment by sursu** [comment]
@cottrell did you manage to fix this?<br><br>

> If I have to guess, this is because your sim account has not been configured for these products

@gidven how did you configure the sim account for these products?

**Comment by gidven** [comment]
Vanilla live accounts have access to our entire multi-asset offering. SIM accounts are limited. In case you want to tinker with these products you can register a account with us.

**Comment by sursu** [comment]
I have a SaxoTraderGO account and a SIM account. The credentials from the former were not accepted at login on developer.saxo.

How can I register for a vanilla live account which would allow me to access e.g. option chains?

**Comment by gidven** [comment]
See [here](https://www.developer.saxo/openapi/learn/writing-an-openapi-application).

**Comment by sursu** [comment]
I have followed the steps outlined there, and I have a couple of questions:

1. What do you call an Application? Is it an algorithm ready to be deployed?
If so, why would one be allowed to "configure up to 10 apps"? Can't those 10 apps be merged in a single app?
<br>

2. It says on [Direct Clients - Request for OpenAPI Application credentials for the LIVE environment](https://www.developer.saxo/openapi/learn/direct-clients-request-for-openapi-application-credentials-for-the-live-environ)

> Make sure you have created and tested your application against our SIM environment

How can I test my application against my SIM environment if I need to have access to a LIVE account in order to access data?
<br>

3. At (2) **Request your LIVE application** at step 3:
> Log in with your LIVE account

How can I login with a LIVE account if I am applying for the LIVE environment in order to get a LIVE account?
<br>
