### ISSUE TITLE
Fetching forex instrument list

### ISSUE THREAD

**Issue by jazarija** [hootnot/saxo_openapi#9]
Hello!

I am following the jupyter guide https://github.com/hootnot/saxo_openapi/blob/master/jupyter/instrumentlookup.ipynb and would like to list the information for all FX pairs. So far I have the following

```
from saxo_openapi import API
from saxo_openapi.exceptions import OpenAPIError
from saxo_openapi.contrib.session import account_info
import saxo_openapi.endpoints.referencedata as rd
from saxo_openapi.definitions.orders import AssetType as AT
import json
import juputil

client = API(access_token='')
ai = account_info(client)
r = rd.instruments.Instruments(params = {'AccountKey': ai.AccountKey, 'KeyWords':'', 'AssetTypes':AT.FxSpot})
D = json.loads(json.dumps( client.request(r)))
```

The problem with this is that D only contains 50 forex pairs. Printing D we also see that there is a' __next:'  with value
`https://gateway.saxobank.com:443/sim/openapi/ref/v1/instruments/?accountkey=UZ126eBOlVCUT0aqBK443s5xA%3D%3D&keywords=&assettypes=FxSpot&$skip=50`

My question is, how could I fetch *all* forex pairs using this API?

**Comment by hootnot** [comment]
Hi, it looks like you need a work-around to get the next 50 by calling the requests instance from the client, like:

```python
client.client.get(D['__next'])
```

(since you named the client 'client', using the member 'client', you get 'client' twice)

Pls let me know if that worked.

I currently don't use the SAXO API, but I'll see to integrate those '__next' requests in a way like the other requests.

**Comment by hootnot** [comment]
you need to check if '__nex't is in the response, if so call client.client.get(...) 

something like:

```python
# the initial request
rv = client.request(r)
while '__next' in rv:
     nextreq = rv['__next']
     resp = client.client.get(nextreq)
     rv = resp.json()
```
Code above is a guess, not verified! and of course you need to do something with the response of the requests before issueing a new request

see requests for possible additional info: https://requests.readthedocs.io/en/master/

**Comment by gidven** [comment]
Hi folks,

Parsing through the `__next` flags won't be necessary if you use the `$top=` query string param instead. The instruments endpoint will return up to 1000 results per response. Pagination is dynamic if more results are found. Considering Saxo offers something on the order of 180 tradable FX crosses, you should be able to retrieve all of them in a single call:

https://gateway.saxobank.com/sim/openapi/ref/v1/instruments/?$top=1000&AssetTypes=FxSpot

Not entirely sure how this translates into the wrapper but I assume something like:

``` Python
r = rd.instruments.Instruments(params = {'AccountKey': ai.AccountKey, 'KeyWords':'', 'AssetTypes':AT.FxSpot, '$top':1000})
```

**Comment by hootnot** [comment]
Hi guys,

the solution posted by Gid should work also and is preferred that way because you don't have to work around issuing non-API requests.

Assuming this is resolved now, I'll close the issue.
